### ISSUE TITLE
repo clean

### ISSUE THREAD

**Issue by brucelane** [artmobilis/ArtMobilis-js#20]
shall we just keep the "www" folder in this repo?
benefits:
- no platform-specific files (visual studio, platform builds, etc)
- gh-pages branch would have index.html ready to go

drawbacks:
- implies each user has to manage his files (including config.xml consistency) on the parent folder on his local machine.
- vs2013 users would need an extra config step

**Comment by ssm2017** [comment]
we need to determine what files are strictly needed to compile the application and ignore the other ones (i will try to install the android sdk to collect them).
i think that the parent folder is required to compile the app.
the issue is only with microsoft noise added by visual studio inside the folders and the files (config.xml is full of microsoft references for example)

**Comment by d-j-a-y** [comment]
I think that the ionic.project file located at /  need to be archived, it's a necessary file to run the project (is 'nt it?)

All other no needed files (ide projects ... ) should be added to personal .gitignore (and also .gitignore indise gitignore i think)

**Comment by brucelane** [comment]
we need all the files below www, but they can be specific to each developer's programming environment
.gitignore might be an option

**Comment by ssm2017** [comment]
knowing that ionic is using several tools to create a project, we need to have the same files to have the same compilation result.
ionic is using : 
- bower : to install javascript libraries
- cordova : to build mobile apps
- gulp : to compile js and sass using tasks
- node : to build the app
- angular : to have a js main engine

the ionic doc is telling us what are the minimum files used : 
see : http://ionicframework.com/docs/guide/installation.html
and scroll to : Create the project
so we need to have the config files for all of these tools.
the issue is when visual studio is adding its own files and folders and the worst is when it is adding microsoft related things inside the standard files.
for example, in config.xml that is needed by cordova, visualstudio is adding things like this : 

```
<vs:plugin name="cordova-plugin-camera" version="1.2.0" xmlns:vs="http://schemas.microsoft.com/appx/2014/htmlapps" />
```

i am actually trying to make a script to build a clean dev environment using linux about this issue.
see : https://github.com/artmobilis/ArtMobilis-js/issues/21
after that, i would be able to define what are the mandatory files and folders to build the project.
for sure, all the ide related files should be ignored.
i hope to be able to show what files are standardly added on the next week.

**Comment by ssm2017** [comment]
i think that this issue is not urgent and we can try to concentrate on the code and then see this issue again later.

but here is what i have seen : 

## root folder

### files
- .bowerrc (standard)
- .editorconfig (standard)
- .gitignore (standard)
- **ArtMobilis2015.proj (visual studio)**
- **ArtMobilis2015.sln (visual studio)**
- **Project_Readme.html (visual studio)**
- README.md (standard)
- bower.json (standard)
- build.json (i don't know)
- config.xml (standard)
- gulpfile.js (standard)
- ionic.project (standard)
- package.json (standard)
- **taco.json (visual studio)**

### folders
- **asset (visual studio)**
- hooks (standard)
- scss (standard)
- www (standard)

## www folder

### files
- **ArtMobilis.jsproj (visual studio)**
- **ArtMobilis.sln (visual studio)**
- **CodeOrganisation.md (should be sent to the wiki and the removed)**
- **config.xml (wrong place, should be removed (visual studio))**
- index.html (standard)

### folders
- css (standard)
- img (standard)
- js (standard)
- lib (standard)
- **merges (visual studio)**
- **res (visual studio)**
- **scripts (should be replaced by js to follow the standards)**
- templates (standard)
- video (non standard)
